// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Project struct {
	ProjectID          int64
	UserID             int64
	Port               sql.NullInt64
	ProjectName        string
	ProjectAvatar      sql.NullString
	ProjectDescription sql.NullString
	ProjectSize        sql.NullInt64
	CreateAt           sql.NullString
	UpdateAt           sql.NullString
}

type User struct {
	UserID       int64
	UserName     string
	PasswordHash string
	Email        string
	UserAvatar   sql.NullString
	CreateAt     sql.NullString
	UpdateAt     sql.NullString
}
