// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type User struct {
	UserID       int64
	UserName     string
	PasswordHash string
	Email        string
	UserAvatar   sql.NullString
	CreateAt     sql.NullString
	UpdateAt     sql.NullString
}
