// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Log struct {
	ID        int64
	LogText   string
	CreatedAt sql.NullString
}

type Notification struct {
	NotificationID      int64
	SenderID            int64
	ReceiverID          int64
	ProjectID           int64
	NotificationContent string
	NotificationStatus  string
	CreateAt            sql.NullString
	UpdateAt            sql.NullString
}

type Project struct {
	ProjectID          int64
	UserID             int64
	ProjectName        string
	ProjectAvatar      sql.NullString
	ProjectDescription sql.NullString
	ProjectSize        sql.NullInt64
	CreateAt           sql.NullString
	UpdateAt           sql.NullString
}

type Security struct {
	ID          int64
	TableName   string
	CreateWhere sql.NullString
	DeleteWhere sql.NullString
	UpdateWhere sql.NullString
	ViewWhere   sql.NullString
}

type Sqls struct {
	ID  int64
	Sql string
}

type User struct {
	UserID       int64
	UserName     string
	PasswordHash string
	Email        string
	UserAvatar   sql.NullString
	CreateAt     sql.NullString
	UpdateAt     sql.NullString
}
