// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"
	"database/sql"
)

const checkDuplicateNotification = `-- name: CheckDuplicateNotification :one
SELECT COUNT(*) FROM notifications 
WHERE sender_id = ? AND receiver_id = ? AND project_id = ? 
AND notification_status IN ('pending', 'agree')
`

type CheckDuplicateNotificationParams struct {
	SenderID   int64
	ReceiverID int64
	ProjectID  int64
}

func (q *Queries) CheckDuplicateNotification(ctx context.Context, arg CheckDuplicateNotificationParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkDuplicateNotification, arg.SenderID, arg.ReceiverID, arg.ProjectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const checkNotificationPermission = `-- name: CheckNotificationPermission :one
SELECT COUNT(*) FROM notifications 
WHERE notification_id = ? AND receiver_id = ? AND notification_status = 'pending'
`

type CheckNotificationPermissionParams struct {
	NotificationID int64
	ReceiverID     int64
}

func (q *Queries) CheckNotificationPermission(ctx context.Context, arg CheckNotificationPermissionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkNotificationPermission, arg.NotificationID, arg.ReceiverID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLogs = `-- name: CountLogs :one
SELECT COUNT(*) FROM _log_
`

func (q *Queries) CountLogs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countQueries = `-- name: CountQueries :one
SELECT COUNT(*) FROM _query_
`

func (q *Queries) CountQueries(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countQueries)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchLogs = `-- name: CountSearchLogs :one
SELECT COUNT(*) FROM _log_ 
WHERE log_text LIKE ?
`

func (q *Queries) CountSearchLogs(ctx context.Context, logText string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSearchLogs, logText)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLog = `-- name: CreateLog :exec
INSERT INTO _log_ (log_text) VALUES (?)
`

func (q *Queries) CreateLog(ctx context.Context, logText string) error {
	_, err := q.db.ExecContext(ctx, createLog, logText)
	return err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
    sender_id, receiver_id, project_id, notification_content, notification_status,
    create_at, update_at
) VALUES (
    ?, ?, ?, ?, ?,
    datetime('now'), datetime('now')
)
RETURNING notification_id, sender_id, receiver_id, project_id, notification_content, notification_status, create_at, update_at
`

type CreateNotificationParams struct {
	SenderID            int64
	ReceiverID          int64
	ProjectID           int64
	NotificationContent string
	NotificationStatus  string
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, createNotification,
		arg.SenderID,
		arg.ReceiverID,
		arg.ProjectID,
		arg.NotificationContent,
		arg.NotificationStatus,
	)
	var i Notification
	err := row.Scan(
		&i.NotificationID,
		&i.SenderID,
		&i.ReceiverID,
		&i.ProjectID,
		&i.NotificationContent,
		&i.NotificationStatus,
		&i.CreateAt,
		&i.UpdateAt,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    user_id, project_name, project_avatar, project_description, project_size, create_at, update_at
) VALUES (
    ?, ?, ?, ?, ?, datetime('now'), datetime('now')
)
RETURNING project_id, user_id, project_name, project_avatar, project_description, project_size, create_at, update_at
`

type CreateProjectParams struct {
	UserID             int64
	ProjectName        string
	ProjectAvatar      sql.NullString
	ProjectDescription sql.NullString
	ProjectSize        sql.NullInt64
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.UserID,
		arg.ProjectName,
		arg.ProjectAvatar,
		arg.ProjectDescription,
		arg.ProjectSize,
	)
	var i Project
	err := row.Scan(
		&i.ProjectID,
		&i.UserID,
		&i.ProjectName,
		&i.ProjectAvatar,
		&i.ProjectDescription,
		&i.ProjectSize,
		&i.CreateAt,
		&i.UpdateAt,
	)
	return i, err
}

const createQuery = `-- name: CreateQuery :one
INSERT INTO _query_ (queries, create_at, update_at)
VALUES (?, datetime('now'), datetime('now'))
RETURNING id, queries, create_at, update_at
`

func (q *Queries) CreateQuery(ctx context.Context, queries string) (Query, error) {
	row := q.db.QueryRowContext(ctx, createQuery, queries)
	var i Query
	err := row.Scan(
		&i.ID,
		&i.Queries,
		&i.CreateAt,
		&i.UpdateAt,
	)
	return i, err
}

const createSecurity = `-- name: CreateSecurity :exec
INSERT INTO _security_ (table_name, create_where, delete_where, update_where, view_where)
VALUES (?, ?, ?, ?, ?)
`

type CreateSecurityParams struct {
	TableName   string
	CreateWhere sql.NullString
	DeleteWhere sql.NullString
	UpdateWhere sql.NullString
	ViewWhere   sql.NullString
}

func (q *Queries) CreateSecurity(ctx context.Context, arg CreateSecurityParams) error {
	_, err := q.db.ExecContext(ctx, createSecurity,
		arg.TableName,
		arg.CreateWhere,
		arg.DeleteWhere,
		arg.UpdateWhere,
		arg.ViewWhere,
	)
	return err
}

const createSql = `-- name: CreateSql :exec
INSERT INTO _sqls_ (sql) VALUES (?)
`

func (q *Queries) CreateSql(ctx context.Context, argSql string) error {
	_, err := q.db.ExecContext(ctx, createSql, argSql)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    user_name, password_hash, email, user_avatar,
    create_at, update_at
) VALUES (
    ?, ?, ?, ?,
    datetime('now'), datetime('now')
)
RETURNING user_id, user_name, password_hash, email, user_avatar, create_at, update_at
`

type CreateUserParams struct {
	UserName     string
	PasswordHash string
	Email        string
	UserAvatar   sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.UserName,
		arg.PasswordHash,
		arg.Email,
		arg.UserAvatar,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserName,
		&i.PasswordHash,
		&i.Email,
		&i.UserAvatar,
		&i.CreateAt,
		&i.UpdateAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE project_id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, projectID int64) error {
	_, err := q.db.ExecContext(ctx, deleteProject, projectID)
	return err
}

const deleteQuery = `-- name: DeleteQuery :exec
DELETE FROM _query_ WHERE id = ?
`

func (q *Queries) DeleteQuery(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteQuery, id)
	return err
}

const deleteSecurity = `-- name: DeleteSecurity :exec
DELETE FROM _security_ WHERE table_name = ?
`

func (q *Queries) DeleteSecurity(ctx context.Context, tableName string) error {
	_, err := q.db.ExecContext(ctx, deleteSecurity, tableName)
	return err
}

const deleteSql = `-- name: DeleteSql :exec
DELETE FROM _sqls_ WHERE id = ?
`

func (q *Queries) DeleteSql(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSql, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE user_id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, userID)
	return err
}

const getCollaborativeProjects = `-- name: GetCollaborativeProjects :many
SELECT p.project_id, p.user_id, p.project_name, p.project_avatar, p.project_description, p.project_size, p.create_at, p.update_at FROM projects p
INNER JOIN notifications n ON p.project_id = n.project_id
WHERE n.receiver_id = ? AND n.notification_status = 'agree'
ORDER BY p.create_at DESC
`

func (q *Queries) GetCollaborativeProjects(ctx context.Context, receiverID int64) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, getCollaborativeProjects, receiverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ProjectID,
			&i.UserID,
			&i.ProjectName,
			&i.ProjectAvatar,
			&i.ProjectDescription,
			&i.ProjectSize,
			&i.CreateAt,
			&i.UpdateAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestSql = `-- name: GetLatestSql :one
SELECT id, sql FROM _sqls_ ORDER BY id DESC LIMIT 1
`

func (q *Queries) GetLatestSql(ctx context.Context) (Sqls, error) {
	row := q.db.QueryRowContext(ctx, getLatestSql)
	var i Sqls
	err := row.Scan(&i.ID, &i.Sql)
	return i, err
}

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT notification_id, sender_id, receiver_id, project_id, notification_content, notification_status, create_at, update_at FROM notifications WHERE notification_id = ? LIMIT 1
`

func (q *Queries) GetNotificationByID(ctx context.Context, notificationID int64) (Notification, error) {
	row := q.db.QueryRowContext(ctx, getNotificationByID, notificationID)
	var i Notification
	err := row.Scan(
		&i.NotificationID,
		&i.SenderID,
		&i.ReceiverID,
		&i.ProjectID,
		&i.NotificationContent,
		&i.NotificationStatus,
		&i.CreateAt,
		&i.UpdateAt,
	)
	return i, err
}

const getNotificationsByReceiver = `-- name: GetNotificationsByReceiver :many
SELECT notification_id, sender_id, receiver_id, project_id, notification_content, notification_status, create_at, update_at FROM notifications WHERE receiver_id = ? ORDER BY create_at DESC
`

func (q *Queries) GetNotificationsByReceiver(ctx context.Context, receiverID int64) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, getNotificationsByReceiver, receiverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.NotificationID,
			&i.SenderID,
			&i.ReceiverID,
			&i.ProjectID,
			&i.NotificationContent,
			&i.NotificationStatus,
			&i.CreateAt,
			&i.UpdateAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotificationsByReceiverAndStatus = `-- name: GetNotificationsByReceiverAndStatus :many
SELECT notification_id, sender_id, receiver_id, project_id, notification_content, notification_status, create_at, update_at FROM notifications WHERE receiver_id = ? AND notification_status = ? ORDER BY create_at DESC
`

type GetNotificationsByReceiverAndStatusParams struct {
	ReceiverID         int64
	NotificationStatus string
}

func (q *Queries) GetNotificationsByReceiverAndStatus(ctx context.Context, arg GetNotificationsByReceiverAndStatusParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, getNotificationsByReceiverAndStatus, arg.ReceiverID, arg.NotificationStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.NotificationID,
			&i.SenderID,
			&i.ReceiverID,
			&i.ProjectID,
			&i.NotificationContent,
			&i.NotificationStatus,
			&i.CreateAt,
			&i.UpdateAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotificationsBySender = `-- name: GetNotificationsBySender :many
SELECT notification_id, sender_id, receiver_id, project_id, notification_content, notification_status, create_at, update_at FROM notifications WHERE sender_id = ? ORDER BY create_at DESC
`

func (q *Queries) GetNotificationsBySender(ctx context.Context, senderID int64) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, getNotificationsBySender, senderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.NotificationID,
			&i.SenderID,
			&i.ReceiverID,
			&i.ProjectID,
			&i.NotificationContent,
			&i.NotificationStatus,
			&i.CreateAt,
			&i.UpdateAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotificationsBySenderAndStatus = `-- name: GetNotificationsBySenderAndStatus :many
SELECT notification_id, sender_id, receiver_id, project_id, notification_content, notification_status, create_at, update_at FROM notifications WHERE sender_id = ? AND notification_status = ? ORDER BY create_at DESC
`

type GetNotificationsBySenderAndStatusParams struct {
	SenderID           int64
	NotificationStatus string
}

func (q *Queries) GetNotificationsBySenderAndStatus(ctx context.Context, arg GetNotificationsBySenderAndStatusParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, getNotificationsBySenderAndStatus, arg.SenderID, arg.NotificationStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.NotificationID,
			&i.SenderID,
			&i.ReceiverID,
			&i.ProjectID,
			&i.NotificationContent,
			&i.NotificationStatus,
			&i.CreateAt,
			&i.UpdateAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT project_id, user_id, project_name, project_avatar, project_description, project_size, create_at, update_at FROM projects WHERE project_id = ? LIMIT 1
`

func (q *Queries) GetProjectByID(ctx context.Context, projectID int64) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByID, projectID)
	var i Project
	err := row.Scan(
		&i.ProjectID,
		&i.UserID,
		&i.ProjectName,
		&i.ProjectAvatar,
		&i.ProjectDescription,
		&i.ProjectSize,
		&i.CreateAt,
		&i.UpdateAt,
	)
	return i, err
}

const getQueryByID = `-- name: GetQueryByID :one
SELECT id, queries, create_at, update_at FROM _query_ WHERE id = ? LIMIT 1
`

func (q *Queries) GetQueryByID(ctx context.Context, id int64) (Query, error) {
	row := q.db.QueryRowContext(ctx, getQueryByID, id)
	var i Query
	err := row.Scan(
		&i.ID,
		&i.Queries,
		&i.CreateAt,
		&i.UpdateAt,
	)
	return i, err
}

const getSecurityByTable = `-- name: GetSecurityByTable :one
SELECT id, table_name, create_where, delete_where, update_where, view_where
FROM _security_
WHERE table_name = ?
`

func (q *Queries) GetSecurityByTable(ctx context.Context, tableName string) (Security, error) {
	row := q.db.QueryRowContext(ctx, getSecurityByTable, tableName)
	var i Security
	err := row.Scan(
		&i.ID,
		&i.TableName,
		&i.CreateWhere,
		&i.DeleteWhere,
		&i.UpdateWhere,
		&i.ViewWhere,
	)
	return i, err
}

const getTeamPermission = `-- name: GetTeamPermission :one
SELECT notification_content, notification_status FROM notifications 
WHERE sender_id = ? AND receiver_id = ? AND project_id = ? 
AND notification_status = 'agree'
LIMIT 1
`

type GetTeamPermissionParams struct {
	SenderID   int64
	ReceiverID int64
	ProjectID  int64
}

type GetTeamPermissionRow struct {
	NotificationContent string
	NotificationStatus  string
}

func (q *Queries) GetTeamPermission(ctx context.Context, arg GetTeamPermissionParams) (GetTeamPermissionRow, error) {
	row := q.db.QueryRowContext(ctx, getTeamPermission, arg.SenderID, arg.ReceiverID, arg.ProjectID)
	var i GetTeamPermissionRow
	err := row.Scan(&i.NotificationContent, &i.NotificationStatus)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT user_id, user_name, password_hash, email, user_avatar, create_at, update_at FROM users
WHERE email = ? LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserName,
		&i.PasswordHash,
		&i.Email,
		&i.UserAvatar,
		&i.CreateAt,
		&i.UpdateAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, user_name, password_hash, email, user_avatar, create_at, update_at FROM users
WHERE user_id = ? LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, userID int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserName,
		&i.PasswordHash,
		&i.Email,
		&i.UserAvatar,
		&i.CreateAt,
		&i.UpdateAt,
	)
	return i, err
}

const getUserByName = `-- name: GetUserByName :one
SELECT user_id, user_name, password_hash, email, user_avatar, create_at, update_at FROM users
WHERE user_name = ? LIMIT 1
`

func (q *Queries) GetUserByName(ctx context.Context, userName string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByName, userName)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserName,
		&i.PasswordHash,
		&i.Email,
		&i.UserAvatar,
		&i.CreateAt,
		&i.UpdateAt,
	)
	return i, err
}

const listAllProjectsForRestore = `-- name: ListAllProjectsForRestore :many
SELECT project_id, user_id, project_name, project_avatar, project_description, project_size, create_at, update_at FROM projects WHERE port IS NOT NULL
`

func (q *Queries) ListAllProjectsForRestore(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listAllProjectsForRestore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ProjectID,
			&i.UserID,
			&i.ProjectName,
			&i.ProjectAvatar,
			&i.ProjectDescription,
			&i.ProjectSize,
			&i.CreateAt,
			&i.UpdateAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllUsers = `-- name: ListAllUsers :many
SELECT user_id, user_name, password_hash, email, user_avatar, create_at, update_at FROM users
`

func (q *Queries) ListAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.UserName,
			&i.PasswordHash,
			&i.Email,
			&i.UserAvatar,
			&i.CreateAt,
			&i.UpdateAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLogs = `-- name: ListLogs :many
SELECT id, log_text, created_at FROM _log_ ORDER BY id DESC LIMIT ? OFFSET ?
`

type ListLogsParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListLogs(ctx context.Context, arg ListLogsParams) ([]Log, error) {
	rows, err := q.db.QueryContext(ctx, listLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Log
	for rows.Next() {
		var i Log
		if err := rows.Scan(&i.ID, &i.LogText, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByUserID = `-- name: ListProjectsByUserID :many
SELECT project_id, user_id, project_name, project_avatar, project_description, project_size, create_at, update_at FROM projects WHERE user_id = ? ORDER BY create_at DESC
`

func (q *Queries) ListProjectsByUserID(ctx context.Context, userID int64) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ProjectID,
			&i.UserID,
			&i.ProjectName,
			&i.ProjectAvatar,
			&i.ProjectDescription,
			&i.ProjectSize,
			&i.CreateAt,
			&i.UpdateAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueries = `-- name: ListQueries :many
SELECT id, queries, create_at, update_at FROM _query_ ORDER BY id DESC LIMIT ? OFFSET ?
`

type ListQueriesParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListQueries(ctx context.Context, arg ListQueriesParams) ([]Query, error) {
	rows, err := q.db.QueryContext(ctx, listQueries, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Query
	for rows.Next() {
		var i Query
		if err := rows.Scan(
			&i.ID,
			&i.Queries,
			&i.CreateAt,
			&i.UpdateAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecurities = `-- name: ListSecurities :many
SELECT id, table_name, create_where, delete_where, update_where, view_where FROM _security_
`

func (q *Queries) ListSecurities(ctx context.Context) ([]Security, error) {
	rows, err := q.db.QueryContext(ctx, listSecurities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Security
	for rows.Next() {
		var i Security
		if err := rows.Scan(
			&i.ID,
			&i.TableName,
			&i.CreateWhere,
			&i.DeleteWhere,
			&i.UpdateWhere,
			&i.ViewWhere,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSqls = `-- name: ListSqls :many
SELECT id, sql FROM _sqls_
`

func (q *Queries) ListSqls(ctx context.Context) ([]Sqls, error) {
	rows, err := q.db.QueryContext(ctx, listSqls)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sqls
	for rows.Next() {
		var i Sqls
		if err := rows.Scan(&i.ID, &i.Sql); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchLogs = `-- name: SearchLogs :many
SELECT id, log_text, created_at FROM _log_ 
WHERE log_text LIKE ? 
ORDER BY id DESC 
LIMIT ? OFFSET ?
`

type SearchLogsParams struct {
	LogText string
	Limit   int64
	Offset  int64
}

func (q *Queries) SearchLogs(ctx context.Context, arg SearchLogsParams) ([]Log, error) {
	rows, err := q.db.QueryContext(ctx, searchLogs, arg.LogText, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Log
	for rows.Next() {
		var i Log
		if err := rows.Scan(&i.ID, &i.LogText, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotificationStatus = `-- name: UpdateNotificationStatus :exec
UPDATE notifications
SET notification_status = ?, update_at = datetime('now')
WHERE notification_id = ?
`

type UpdateNotificationStatusParams struct {
	NotificationStatus string
	NotificationID     int64
}

func (q *Queries) UpdateNotificationStatus(ctx context.Context, arg UpdateNotificationStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateNotificationStatus, arg.NotificationStatus, arg.NotificationID)
	return err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET
    project_name = COALESCE(?, project_name),
    project_avatar = COALESCE(?, project_avatar),
    project_description = COALESCE(?, project_description),
    update_at = datetime('now')
WHERE project_id = ?
RETURNING project_id, user_id, project_name, project_avatar, project_description, project_size, create_at, update_at
`

type UpdateProjectParams struct {
	ProjectName        string
	ProjectAvatar      sql.NullString
	ProjectDescription sql.NullString
	ProjectID          int64
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProject,
		arg.ProjectName,
		arg.ProjectAvatar,
		arg.ProjectDescription,
		arg.ProjectID,
	)
	var i Project
	err := row.Scan(
		&i.ProjectID,
		&i.UserID,
		&i.ProjectName,
		&i.ProjectAvatar,
		&i.ProjectDescription,
		&i.ProjectSize,
		&i.CreateAt,
		&i.UpdateAt,
	)
	return i, err
}

const updateProjectSize = `-- name: UpdateProjectSize :exec
UPDATE projects SET project_size = ?, update_at = datetime('now') WHERE project_id = ?
`

type UpdateProjectSizeParams struct {
	ProjectSize sql.NullInt64
	ProjectID   int64
}

func (q *Queries) UpdateProjectSize(ctx context.Context, arg UpdateProjectSizeParams) error {
	_, err := q.db.ExecContext(ctx, updateProjectSize, arg.ProjectSize, arg.ProjectID)
	return err
}

const updateQuery = `-- name: UpdateQuery :exec
UPDATE _query_
SET queries = ?, update_at = datetime('now')
WHERE id = ?
`

type UpdateQueryParams struct {
	Queries string
	ID      int64
}

func (q *Queries) UpdateQuery(ctx context.Context, arg UpdateQueryParams) error {
	_, err := q.db.ExecContext(ctx, updateQuery, arg.Queries, arg.ID)
	return err
}

const updateSecurity = `-- name: UpdateSecurity :exec
UPDATE _security_
SET create_where = ?, delete_where = ?, update_where = ?, view_where = ?
WHERE table_name = ?
`

type UpdateSecurityParams struct {
	CreateWhere sql.NullString
	DeleteWhere sql.NullString
	UpdateWhere sql.NullString
	ViewWhere   sql.NullString
	TableName   string
}

func (q *Queries) UpdateSecurity(ctx context.Context, arg UpdateSecurityParams) error {
	_, err := q.db.ExecContext(ctx, updateSecurity,
		arg.CreateWhere,
		arg.DeleteWhere,
		arg.UpdateWhere,
		arg.ViewWhere,
		arg.TableName,
	)
	return err
}

const updateSql = `-- name: UpdateSql :exec
UPDATE _sqls_
SET sql = ?
WHERE id = ?
`

type UpdateSqlParams struct {
	Sql string
	ID  int64
}

func (q *Queries) UpdateSql(ctx context.Context, arg UpdateSqlParams) error {
	_, err := q.db.ExecContext(ctx, updateSql, arg.Sql, arg.ID)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    user_name = COALESCE(?, user_name),
    password_hash = COALESCE(?, password_hash),
    user_avatar = COALESCE(?, user_avatar),
    update_at = datetime('now')
WHERE user_id = ?
RETURNING user_id, user_name, password_hash, email, user_avatar, create_at, update_at
`

type UpdateUserParams struct {
	UserName     string
	PasswordHash string
	UserAvatar   sql.NullString
	UserID       int64
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.UserName,
		arg.PasswordHash,
		arg.UserAvatar,
		arg.UserID,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserName,
		&i.PasswordHash,
		&i.Email,
		&i.UserAvatar,
		&i.CreateAt,
		&i.UpdateAt,
	)
	return i, err
}
