// src/embed_assets.ts
// 作用: 将图片Base64编码，替换Markdown中的图片路径，清理指定内容，并生成内嵌资源文件。

import { readdir, readFile, writeFile } from 'fs/promises';
import * as path from 'path';
import { Buffer } from 'buffer';

// --- 配置路径和文件列表 ---
// 脚本位于 src/，docs/ 也在 src/，所以直接访问 'docs' 
const ASSETS_ROOT = path.resolve(import.meta.dir, 'docs'); 
const MD_FILES = ['intro.md', 'library.md', 'tutorial.md'];
const OUTPUT_FILE = path.resolve(import.meta.dir, 'generated_assets.ts'); // 输出到 src/generated_assets.ts
const IMAGES_DIR_NAME = 'imgs';
const IMAGES_DIR = path.resolve(ASSETS_ROOT, IMAGES_DIR_NAME);

// --- 辅助函数：获取 MIME 类型 ---
const getMimeType = (filePath: string): string => {
  const ext = path.extname(filePath).toLowerCase();
  switch (ext) {
    case '.png': return 'image/png';
    case '.jpg':
    case '.jpeg': return 'image/jpeg';
    case '.gif': return 'image/gif';
    default: return 'application/octet-stream';
  }
};

// --- 核心函数：内嵌资源并修改 Markdown ---
async function embedAssets(): Promise<void> {
  const assets: Record<string, string> = {};
  const imageMap: Record<string, string> = {};

  // 1. 查找并转换所有图片为 Base64 Data URI
  console.log('--- 1. Processing Images to Base64 ---');
  console.log(`Checking image path: ${IMAGES_DIR}`); // 调试信息
  try {
    const imageFiles = (await readdir(IMAGES_DIR)).filter(name => /\.(png|jpg|jpeg|gif)$/i.test(name));
    
    for (const fileName of imageFiles) {
      const fullPath = path.join(IMAGES_DIR, fileName);
      // Markdown中引用的相对路径作为键 (例如: /docs/imgs/Database_create.png)
      const assetKey = path.join('/docs', IMAGES_DIR_NAME, fileName).replace(/\\/g, '/'); 
      
      const content = await readFile(fullPath);
      const base64 = Buffer.from(content).toString('base64');
      const mimeType = getMimeType(fileName);
      
      imageMap[assetKey] = `data:${mimeType};base64,${base64}`;
      console.log(`- Embedded: ${assetKey}`);
    }
  } catch (e) {
      console.error(`Error reading image directory (${IMAGES_DIR}).`, e);
      return;
  }

  // 2. 处理并修改 Markdown 文件
  console.log('\n--- 2. Processing Markdown Files ---');
  for (const mdName of MD_FILES) {
    const mdPath = path.join(ASSETS_ROOT, mdName);
    let mdContent = await readFile(mdPath, 'utf-8');

    // 2a. 清理 tutorial.md 中的测试 div
    if (mdName === 'tutorial.md') {
       // 删除 <div id="test">...</div> 及其内部内容
       mdContent = mdContent.replace(/<div\s+id="test"[\s\S]*?<\/div>/g, ''); 
       console.log(`- Cleaned test div in: ${mdName}`);
    }

    // 2b. 替换 Markdown 中的图片路径为 Base64 Data URI
    mdContent = mdContent.replace(/!\[.*?\]\((.*?)\)/g, (match, url) => {
      const key = url.trim(); 
      const base64Uri = imageMap[key];
      
      if (base64Uri) {
        return match.replace(url, base64Uri);
      }
      console.warn(`⚠️ Warning: Image not found in map: ${key} (in ${mdName})`);
      return match;
    });

    const exportName = mdName.split('.')[0] + '_md_content';
    assets[exportName] = mdContent;
    console.log(`- Markdown processed: ${mdName}`);
  }

  // 3. 生成 TypeScript 文件
  console.log('\n--- 3. Generating generated_assets.ts ---');
  let tsContent = `// This file is auto-generated by embed_assets.ts\n\n`;
  for (const [key, value] of Object.entries(assets)) {
    tsContent += `export const ${key} = \`${value.replace(/`/g, '\\`').replace(/\$/g, '\\$')}\`;\n`;
  }
  
  await writeFile(OUTPUT_FILE, tsContent);
  console.log(`\n✅ Assets embedded successfully into ${OUTPUT_FILE}`);
}

embedAssets().catch(console.error);
