// 作用: 将小图片Base64编码内嵌，大图片保留路径，清理指定内容，并生成独立的内嵌资源文件。
//应该在上一级目录中
import { readdir, readFile, writeFile } from 'fs/promises';
import * as path from 'path';
import { Buffer } from 'buffer';

// --- 配置路径和文件列表 ---
const ASSETS_ROOT = path.resolve(import.meta.dir, 'docs'); 
const MD_FILES = ['intro.md', 'library.md', 'tutorial.md'];
const IMAGES_DIR_NAME = 'imgs';
const IMAGES_DIR = path.resolve(ASSETS_ROOT, IMAGES_DIR_NAME);
// --- 新增配置：Base64 嵌入阈值 (10KB) ---
const MAX_BASE64_SIZE_KB = 10;
const MAX_BASE64_SIZE_BYTES = MAX_BASE64_SIZE_KB * 1024;


// --- 辅助函数：获取 MIME 类型 ---
const getMimeType = (filePath: string): string => {
  const ext = path.extname(filePath).toLowerCase();
  switch (ext) {
    case '.png': return 'image/png';
    case '.jpg':
    case '.jpeg': return 'image/jpeg';
    case '.gif': return 'image/gif';
    default: return 'application/octet-stream';
  }
};

// --- 核心函数：内嵌资源并修改 Markdown ---
async function embedAssets(): Promise<void> {
  const imageMap: Record<string, string | null> = {}; // 存储 Base64 或 null (表示忽略)

  // 1. 查找并转换所有图片
  console.log('--- 1. Converting Images to Base64 (Max 10KB) ---');
  try {
    const imageFiles = await readdir(IMAGES_DIR);
    for (const fileName of imageFiles) {
      const filePath = path.join(IMAGES_DIR, fileName);
      const fileData = await readFile(filePath);
      const key = `${IMAGES_DIR_NAME}/${fileName}`; 

      if (fileData.length <= MAX_BASE64_SIZE_BYTES) {
        // 小于阈值，进行 Base64 编码
        const mimeType = getMimeType(filePath);
        imageMap[key] = `data:${mimeType};base64,${fileData.toString('base64')}`;
        console.log(`- Base64 Embed (Small): ${fileName} (${(fileData.length / 1024).toFixed(1)} KB)`);
      } else {
        // 大于阈值，不进行 Base64，保留路径
        imageMap[key] = null;
        console.log(`- Path Retained (Large): ${fileName} (${(fileData.length / 1024).toFixed(1)} KB)`);
      }
    }
  } catch (error) {
    console.error('Error reading image directory:', error);
    // 允许脚本继续运行
  }


  // 2. 处理并修改 Markdown 文件，并生成独立的 TS 文件
  console.log('\n--- 2. Processing and Generating Individual MD Files ---');
  for (const mdName of MD_FILES) {
    const mdPath = path.join(ASSETS_ROOT, mdName);
    let mdContent = await readFile(mdPath, 'utf-8');

    // 2a. 清理 tutorial.md 中的测试 div
    if (mdName === 'tutorial.md') {
       // 语法修正后的代码
       mdContent = mdContent.replace(/<div\s+id="test"[\s\S]*?<\/div>/g, ''); 
       console.log(`- Cleaned test div in: ${mdName}`);
    }

    // 2b. 替换 Markdown 中的图片路径
    mdContent = mdContent.replace(/!\\[.*?\\]\\((.*?)\\)/g, (match, url) => {
      // url 是 Markdown 中原始的图片路径，例如 /docs/imgs/file.png 或 imgs/file.png
      const key = url.trim().replace('/docs/', ''); // 移除 /docs/ 前缀
      const base64Uri = imageMap[key];
      
      if (base64Uri === null) {
        // 大图：不替换，保留原始路径 (由浏览器单独加载)
        return match; 
      } else if (base64Uri) {
        // 小图：替换为 Base64
        return match.replace(url, base64Uri);
      }
      // 图片未找到或未在 imgs 目录下，保持原始链接
      console.warn(`⚠️ Warning: Image not processed or found in map: ${key} (in ${mdName})`);
      return match;
    });

    // 3. 生成 TypeScript 文件 (用于动态导入)
    const exportName = mdName.split('.')[0] + '_md_content';
    const outputFilePath = path.join(ASSETS_ROOT, `${exportName}.ts`);
    
    let fileContent = `// This file is auto-generated by embed_assets.ts\n\n`;
    // 使用反引号和转义
    fileContent += `export const ${exportName} = \`${mdContent.replace(/`/g, '\\`')}\`;\n`; 

    await writeFile(outputFilePath, fileContent, 'utf-8');
    console.log(`- Generated: ${outputFilePath}`);
  }

  console.log('\n✅ Markdown assets embedding complete.');
}

embedAssets().catch(err => {
  console.error('An error occurred during asset embedding:', err);
  process.exit(1);
});
