// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Security struct {
	ID          int64
	TableName   string
	CreateWhere sql.NullString
	DeleteWhere sql.NullString
	UpdateWhere sql.NullString
	ViewWhere   sql.NullString
}

type Sqls struct {
	ID  int64
	Sql string
}
